apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"  # Usando variável para o nome
spec:
  replicas: {{ .Values.replicaCount }}  # Referenciando o valor do replicaCount
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"  # Usando variável para o nome
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"  # Usando variável para o nome
    spec:
      containers:
        - name: "{{ .Release.Name }}"  # Usando variável para o nome
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  # Usando variáveis para o repositório e a tag
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.json  # Ajuste para o caminho desejado
              subPath: appsettings.json
      volumes:
        - name: appsettings-volume
          secret:
            secretName: "{{ .Release.Name }}-appsettings"  # Usando variável para o nome
