apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-appsettings"  # Usando variável para o nome
type: Opaque
data:
  appsettings.json: {{ .Files.Get "configs/aovivo/appsettings.json" | b64enc | quote }}  # Lê o arquivo e codifica