apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-appsettings"
type: Opaque
data:
  appsettings.json: {{ .Files.Get (printf "configs/%s/appsettings.json" .Values.environment) | b64enc | quote }}