apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-appsettings"
type: Opaque
data:
  appsettings.json: |
    # Ambiente: {{ .Values.environment }}
    {{ .Files.Get "configs/{{ .Values.environment }}/appsettings.json" | b64enc | quote }}