# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}  # Deve ser LoadBalancer ou NodePort para acesso externo
  ports:
    - port: {{ .Values.service.port }}  # Porta exposta pelo serviço
      targetPort: {{ .Values.service.targetPort }}  # Porta onde o contêiner está escutando
      protocol: TCP
  selector:
    app: {{ .Release.Name }}