apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}  # Usar ClusterIP, conforme especificado no values.yaml
  ports:
    - name: http-port
      port: {{ .Values.service.ports[0].port }}         # Porta exposta pelo serviço
      targetPort: {{ .Values.service.ports[0].targetPort }}  # Porta onde sua aplicação está rodando dentro do contêiner
  selector:
    app: {{ .Release.Name }}