apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-port
      port: {{ .Values.service.port }}         # Porta exposta pelo serviço
      targetPort: {{ .Values.service.targetPort }}  # Porta interna da aplicação
  selector:
    app: {{ .Release.Name }}