apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}  # Será ClusterIP
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}           # Porta exposta pelo serviço (agora 80)
      targetPort: {{ .targetPort }}  # Porta onde o contêiner está escutando
      protocol: TCP
{{- end }}
  selector:
    app: {{ .Release.Name }}